config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, except: %i[edit update]
  resource :search, only: %i[show create]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end

    resource :dashboard

    resources :tickets
    resources :routes
  end

  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :title, presence: true

  before_validation :set_title

  def start_time
    railway_stations.ordered.first.departure_time_in(self)
  end

  def end_time
    railway_stations.ordered.last.arrival_time_in(self)
  end

  private

  def set_title
    self.title = "#{railway_stations.first.name} - #{railway_stations.last.name}"
  end
end

app/controllers/admin/routes_controller.rb
class Admin::RoutesController < Admin::BaseController
  before_action :set_route, only: %i[show edit update destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to admin_route_path(@route), notice: t('controllers.created', resource_name: @route.model_name.human)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to admin_routes_path, notice: t('controllers.updated', resource_name: @route.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to admin_routes_path, notice: t('controllers.destroyed', resource_name: @route.model_name.human)
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:title, railway_station_ids: [])
  end
end

app/views/admin/routes/_form.html.slim
.form
  = form_for [:admin, route], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f|
    = render 'common/errors', resource: route
    fieldset.form-group
      = f.label t('.railway_stations')
      = f.collection_select :railway_station_ids, RailwayStation.order(:name), :id, :name, {}, {multiple: true}
    = f.submit t('.action', action: route.new_record? ? t('common.new') : t('common.edit')), class: 'btn btn-primary btn-sm'

app/views/admin/routes/_route_stations.html.slim
table
  thead
    tr
      th = t('.name')
      th = t('.position')
      th = t('.time')
  tbody
    - @route.railway_stations.ordered.each do |station|
      tr
        td = station.name
        td
          = form_tag update_position_admin_railway_station_path(station), method: :patch do
            .field
              = number_field_tag :position, station.position_in(@route)
              = hidden_field_tag :route_id, @route.id
              = submit_tag t('.change_position'), class: 'btn btn-primary btn-sm'
        td
          = form_tag update_time_admin_railway_station_path(station), method: :patch do
            .field
              = time_field_tag :arrival_time, station.arrival_time_in(@route)
              = time_field_tag :departure_time, station.departure_time_in(@route)
              = hidden_field_tag :route_id, @route.id
              = submit_tag t('.change_time'), class: 'btn btn-primary btn-sm'


    

app/views/admin/routes/_route_trains.html.slim
- route.trains.each do |train|
  ul
    li = train.number

app/views/admin/routes/edit.html.slim
.container
  .card
    .card-header
      h3 = t('.title')
    .card-text
      .card-block
        = render 'form', route: @route, hidden: false
    .card-footer
      = link_to t('common.show'), admin_route_path(@route)
      '  |
      = link_to t('common.back'), admin_routes_path

app/views/admin/routes/index.html.slim
.container
  h1
    = t('admin.dashboards.show.routes')
  table
    thead
      tr
        th = t('common.route_title')
        th[colspan="3"]
    tbody
      - @routes.each do |route|
        tr
          td
            div id="route_title_#{route.id}"
              = route.title
            = render 'form', route: route, hidden: true
          td
            .btn.btn-outline-success.btn-sm = link_to t('common.show'), admin_route_path(route)
          td
            .btn.btn-outline-info.btn-sm = link_to t('common.edit'), '', class: 'edit_route', data: { route_id: route.id}
          td
            .btn.btn-outline-danger.btn-sm = link_to t('common.destroy'), admin_route_path(route), method: :delete, data: { confirm: t('common.are_you_sure') }
  br
  = link_to t('common.new'), new_admin_route_path

app/views/admin/routes/new.html.slim
.container
  .card
    .card-header
      h1
        = t('.title')
    .card-text
      .card-block
        = render 'form', route: @route, hidden: false
    .card-footer
      = link_to t('common.back'), admin_routes_path

app/views/admin/routes/show.html.slim
.container
  .card
    .card-header
      h2 = t('.title')
    .card-text
      .card-block
        ul
          li
            = t('.name')
            ' :
            =< @route.title
          li
            = t('.route_stations')
            - if @route.railway_stations.empty?
              = t('.route_no_stations')
            - else
              = render 'admin/routes/route_stations'
          li
            = t('.assigned_trains')
            - if @route.trains.empty?
              br
              = t('.route_no_trains')
            - else
              = render 'admin/routes/route_trains', route: @route
    .card-footer
      = link_to t('common.edit'), edit_admin_route_path(@route)
      |  |
      = link_to t('common.back'), admin_routes_path