config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, except: %i[edit update]
  resource :search, only: %i[show create]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end

    resource :dashboard

    resources :tickets
    resources :routes
  end

  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :train
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :end_station, class_name: 'RailwayStation', foreign_key: :end_station_id

  validates :number, presence: true, uniqueness: true
  validates :passenger, presence: true

  before_validation :set_number
  after_create :buy_notification
  after_destroy :cancel_notification

  def route_name
    "#{start_station.name} - #{end_station.name}"
  end

  private

  def buy_notification
    TicketsMailer.buy_ticket(self.user, self).deliver_now
  end

  def cancel_notification
    TicketsMailer.cancel_ticket(self.user, self).deliver_now
  end

  def set_number
    self.number ||= [*'0'..'9', *'A'..'Z'].sample(10).join
  end
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::BaseController
  before_action :set_ticket, only: %i[show edit update destroy]

  def index
    @tickets = Ticket.all
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      redirect_to admin_ticket_path(@ticket), notice: t('controllers.created', resource_name: @ticket.model_name.human)
    else
      render :new
    end
  end

  def update
    if @ticket.update(ticket_params)
      redirect_to admin_tickets_url, notice: t('controllers.updated', resource_name: @ticket.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @ticket.destroy
    redirect_to admin_tickets_url, notice: t('controllers.destroyed', resource_name: @ticket.model_name.human)
  end

  private
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:user_id, :number, :passenger, :passport, :train_id, :start_station_id, :end_station_id)
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: %i[show edit destroy]


  def index
    @tickets = current_user.tickets.all
  end

  def show
  end

  def new
    @ticket = current_user.tickets.new
  end

  def create
    @ticket = current_user.tickets.new(ticket_params)
    if @ticket.save
      redirect_to @ticket, notice: t('controllers.created', resource_name: @ticket.model_name.human)
    else
      render :new
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_url, notice: t('controllers.destroyed', resource_name: @ticket.model_name.human)
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  def ticket_params
    params.require(:ticket).permit(:number, :passenger, :passport, :train_id, :start_station_id, :end_station_id)
  end

end

app/views/admin/tickets/_form.html.slim
.container
  .form
    = form_for [:admin, @ticket] do |f|
      = render 'common/errors', resource: @ticket
      fieldset.form-group
        = f.label :train
        = f.collection_select :train_id, Train.all, :id, :number, {prompt: t('.train_prompt')}, {class: 'custom-select'}
      fieldset.form-group
        = f.label :start_station
        = f.collection_select :start_station_id, RailwayStation.all, :id, :name, {prompt: t('searches.show.prompt')}, {class: 'custom-select'}
      fieldset.form-group
        = f.label :end_station
        = f.collection_select :end_station_id, RailwayStation.all, :id, :name, {prompt: t('searches.show.prompt')}, {class: 'custom-select'}
      fieldset.form-group
        = f.label :user
        = f.collection_select :user_id, User.all, :id, :name, {prompt: t('.user_prompt')}, {class: 'custom-select'}
      fieldset.form-group
        = f.label :passenger
        = f.text_field :passenger, class: 'form-control'
      fieldset.form-group
          = f.label :passport
          = f.text_field :passport, class: 'form-control'
      = f.submit t('.action', action: @ticket.new_record? ? t('common.new') : t('common.edit')), class: 'btn btn-primary btn-sm'

app/views/admin/tickets/edit.html.slim
.container
  .card
    .card-header
      h3 = t('.title')
    .card-text
      .card-block
        = render 'form'
    .card-footer
      = link_to t('common.show'), admin_ticket_path(@ticket)
      '  |
      = link_to t('common.back'), admin_tickets_path

app/views/admin/tickets/index.html.slim
.container
  h2 = t('.title')
  table
    thead.thead-inverse
      tr
        th = t('.user')
        th = t('.ticket_number')
        th = t('.passenger')
        th = t('.passport')
        th = t('.train_number')
        th = t('.start_station')
        th = t('.end_station')
        th[colspan="3"]
    tbody
      - @tickets.each do |ticket|
        tr
          td = ticket.user.name
          td = ticket.number
          td = ticket.passenger
          td = ticket.passport
          td = ticket.train.number
          td = ticket.start_station.name
          td = ticket.end_station.name
          td
            .btn.btn-outline-success.btn-sm = link_to t('common.show'), admin_ticket_path(ticket)
          td
            .btn.btn-outline-info.btn-sm = link_to t('common.edit'), edit_admin_ticket_path(ticket)
          td
            .btn.btn-outline-danger.btn-sm = link_to t('common.destroy'), admin_ticket_path(ticket), data: { confirm: t('common.are_you_sure') }, method: :delete

  br

  = link_to t('common.new'), new_admin_ticket_path

app/views/admin/tickets/new.html.slim
.container
  .card
    .card-header
      h1
        = t('.title')
    .card-text
      .card-block
        = render 'form', ticket: @ticket
    .card-footer
      = link_to t('common.back'), admin_tickets_path

app/views/admin/tickets/show.html.slim
.container
  .card
    .card-header
      h3 = t('tickets.show.title', ticket_number: @ticket.number)
    .card-text
      p
        ul
          li
            strong = t('tickets.index.passenger')
            ' :
            =< @ticket.passenger
          li
            strong = t('tickets.index.passport')
            ' :
            =< @ticket.passport
          li
            strong = t('tickets.show.journey_data')
            table
              thead
                tr
                  th = t('common.train_number')
                  th = t('searches.show.start_station')
                  th = t('searches.show.end_station')
              tbody
                tr
                  td = @ticket.train.number
                  td = @ticket.start_station.name
                  td = @ticket.end_station.name

  => link_to t('common.search'), search_path
  ' |
  =<> link_to t('common.back'), admin_tickets_path
  ' |
  =< link_to t('common.edit'), edit_admin_ticket_path(@ticket)