config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, except: %i[edit update]
  resource :search, only: %i[show create]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end

    resource :dashboard

    resources :tickets
    resources :routes
  end

  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carriage.rb
class Carriage < ApplicationRecord
  belongs_to :train

  validates :number, presence: true
  validates :number, uniqueness: { scope: :train_id }
  before_validation :set_number, on: :create

  scope :sorted, -> (sort_from_head) { sort_from_head ? order(number: :desc) : order(number: :asc) }

  protected

  def set_number
    self.number = train.carriages.count + 1
  end
end

app/models/carriages/economy_carriage.rb
class EconomyCarriage < Carriage
  validates :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats, presence: true
end

app/models/carriages/saloon_carriage.rb
class SaloonCarriage < Carriage
  validates :top_seats, :bottom_seats, presence: true
end

app/models/carriages/sitting_carriage.rb
class SittingCarriage < Carriage
  validates :sitting_seats, presence: true
end

app/models/carriages/sleeping_carriage.rb
class SleepingCarriage < Carriage
  validates :bottom_seats, presence: true
end

app/controllers/admin/carriages_controller.rb
class Admin::CarriagesController < Admin::BaseController
  before_action :set_carriage, only: %i[show edit update destroy]
  before_action :set_train, only: %i[index new create]

  def index
    @carriages = @train.carriages.all
  end

  def show
    @carriage = Carriage.find(params[:id])
  end

  def new
    @carriage = Carriage.new
  end

  def edit
  end

  def create
    @carriage = @train.carriages.new(carriage_params)
    if @carriage.save
      redirect_to admin_train_path(@train), notice: t('controllers.created', resource_name: @carriage.model_name.human)
    else
      render :new
    end
  end

  def update
    if @carriage.update(carriage_params)
      redirect_to admin_carriage_path(@carriage ), notice: t('controllers.updated', resource_name: @carriage.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @carriage.destroy
    redirect_to admin_carriages_url, notice: t('controllers.destroyed', resource_name: @carriage.model_name.human)
  end

  private

  def set_train
    @train = Train.find(params[:train_id])
  end

  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  def carriage_params
    params.require(:carriage).permit(:number, :train_id, :type, :top_seats, :bottom_seats,\
                                     :side_top_seats, :side_bottom_seats, :sitting_seats)
  end
end

app/views/admin/carriages/_economy_carriage.html.slim
= t('admin.carriages.carriage.top_seats')
' :
= @carriage.top_seats
br
= t('admin.carriages.carriage.bottom_seats')
' :
= @carriage.bottom_seats
br
= t('admin.carriages.carriage.side_top_seats')
' :
= @carriage.side_top_seats
br
= t('admin.carriages.carriage.side_bottom_seats')
' :
= @carriage.side_bottom_seats

app/views/admin/carriages/_form.html.slim
.container
  .form
    = form_for [:admin, @train, @carriage.becomes(Carriage)] do |f|
      = render 'common/errors', resource: @carriage
        = f.hidden_field :train_id, @train.id
      fieldset.form-group
        = f.label t('.type')
        = f.select :type, ([['Saloon', SaloonCarriage.name], ['Economy', EconomyCarriage.name],\
                            ['Sleeping', SleepingCarriage.name], ['Sitting', SittingCarriage.name]])\
                            , {prompt: t('.type_prompt')}, {class: 'custom-select'}
      div id="bottom" style="display:none"
        fieldset.form-group
          = f.label t('admin.carriages.carriage.bottom_seats')
          = f.number_field :bottom_seats, class: 'form-control'
      div id="top" style="display:none"
        fieldset.form-group
          = f.label t('admin.carriages.carriage.top_seats')
          = f.number_field :top_seats, class: 'form-control'
      div id="economy" style="display:none"
        fieldset.form-group
          = f.label t('admin.carriages.carriage.side_bottom_seats')
          = f.number_field :side_bottom_seats, class: 'form-control'
        fieldset.form-group
          = f.label t('admin.carriages.carriage.side_top_seats')
          = f.number_field :side_top_seats, class: 'form-control'
      div id="sitting" style="display:none"
        fieldset.form-group
          = f.label t('admin.carriages.carriage.sitting_seats')
          = f.number_field :sitting_seats, class: 'form-control'
      = f.submit t('.action', action: @carriage.new_record? ? t('common.new') : t('common.edit')), class: 'btn btn-primary btn-sm'

app/views/admin/carriages/_saloon_carriage.html.slim
= t('admin.carriages.carriage.top_seats')
' :
= @carriage.top_seats
br
= t('admin.carriages.carriage.bottom_seats')
' :
= @carriage.bottom_seats

app/views/admin/carriages/_sitting_carriage.html.slim
= t('admin.carriages.carriage.sitting_seats')
' :
= @carriage.sitting_seats

app/views/admin/carriages/_sleeping_carriage.html.slim
= t('admin.carriages.carriage.bottom_seats')
' :
= @carriage.bottom_seats

app/views/admin/carriages/edit.html.slim
.container
  .card
    .card-header
      h3 = t('.title')
    .card-text
      .card-block
        = render 'form'
    .card-footer
      = link_to t('common.show'), admin_carriage_path(@carriage)
      '  |
      = link_to t('common.back'), admin_train_path(@carriage.train)

app/views/admin/carriages/index.html.slim
h1 All Carriages
table
  thead
    tr
      th Number
      th Class
      th Train
      th[colspan="3"] Actions
  tbody
    - @carriages.each do |carriage|
      tr
        td = carriage.number
        td = carriage.model_name.human
        td = carriage.train.number
        td = link_to 'Show', admin_carriage_path(carriage)
        td = link_to 'Edit', edit_admin_carriage_path(carriage)
        td = link_to 'Destroy', admin_carriage_path(carriage), data: {confirm: 'Are you sure?'}, method: :delete
br

= link_to 'New Carriage', new_admin_train_carriage_path

app/views/admin/carriages/new.html.slim
.container
  h1
    = t('.title')
  == render 'form', carriage: @carriage

app/views/admin/carriages/show.html.slim
.container
  .card
    .card-header
      h2 = t('.title', carriage_number: @carriage.number, train_number: @carriage.train.number)
    .card-text
      .card-block
        br
          strong
            = t('.class')
            ' :
            =< @carriage.model_name.human
        br
          strong
            = t('.seats')
          br
            = render @carriage.type.underscore
    .card-footer
      = link_to t('common.edit'), edit_admin_carriage_path(@carriage)
      '  |
      = link_to t('common.back'), admin_train_path(@carriage.train)