config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tickets, except: %i[edit update]
  resource :search, only: %i[show create]

  namespace :admin do
    resources :trains do
      resources :carriages, shallow: true
    end

    resources :railway_stations do
      patch :update_position, on: :member
      patch :update_time, on: :member
    end

    resource :dashboard

    resources :tickets
    resources :routes
  end

  get 'welcome/index'
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
class Train < ApplicationRecord
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id, required: false
  belongs_to :route, required: false
  has_many :tickets
  has_many :carriages

  validates :number, presence: true, uniqueness: true

  scope :train_route_station, ->(station) { joins(route: :railway_stations).where('railway_station_id = ?', station)}

  def sorted_carriages
    carriages.sorted(sort_from_head)
  end

  def seats_info(carriage_type, seats)
    carriages.where(type: carriage_type).sum(seats)
  end
end

app/controllers/admin/trains_controller.rb
class Admin::TrainsController < Admin::BaseController
  before_action :set_train, only: %i[show edit update destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def edit
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to admin_trains_path, notice: t('controllers.created', resource_name: @train.model_name.human)
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to admin_trains_path, notice: t('controllers.updated', resource_name: @train.model_name.human)
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to admin_trains_url, notice: t('controllers.destroyed', resource_name: @train.model_name.human)
  end

  private
  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id, :sort_from_head)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/admin/trains/_form.html.slim
.form
  = form_for [:admin, train], html: { style: "display: #{hidden ? 'none' : 'block'}" } do |f|
    = render 'common/errors', resource: train
    fieldset.form-group
      = f.label :number
      = f.text_field :number, class: 'form-control'
    fieldset.form-group
      = f.label :sort_from_head
      = f.check_box :sort_from_head, class: 'form-control'
    fieldset.form-group
      = f.label :current_station
      = f.collection_select :current_station_id, RailwayStation.order(:name), :id, :name, {prompt: t('searches.show.prompt')}, {class: 'custom-select'}
    fieldset.form-group
      = f.label :route
      = f.collection_select :route_id, Route.order(:title), :id, :title, {prompt: t('.route_prompt')}, {class: 'custom-select'}
    = f.submit t('.submit', action: train.new_record? ? t('common.new') : t('common.edit')), class: 'btn btn-primary btn-sm'

app/views/admin/trains/_train.html.slim
tr
  td
    div id="train_number_#{train.id}"
      = train.number
    = render 'form', train: train, hidden: true
  td
    .btn.btn-outline-success.btn-sm = link_to t('common.show'), admin_train_path(train)
  td
    .btn.btn-outline-info.btn-sm = link_to t('common.edit'), '', class: 'edit_train', data: { train_id: train.id}
  td
    .btn.btn-outline-danger.btn-sm = link_to t('common.destroy'), admin_train_path(train), method: :delete, data: { confirm: t('common.are_you_sure') }

app/views/admin/trains/edit.html.slim
.container
  .card
    .card-header
      h3 = t('.title')
    .card-text
      .card-block
        = render 'form', train: @train, hidden: false
    .card-footer
      = link_to t('common.show'),admin_train_path(@train)
      |  |
      = link_to t('common.back'), admin_trains_path

app/views/admin/trains/index.html.slim
.container
  h1 = t('.title')
  table
    thead
      tr
        th = t('common.train_number')
        th = t('.current_station')
        th = t('common.route_title')
        th[colspan="3"]
    tbody
      = render @trains
  br
  = link_to t('common.new'), new_admin_train_path

app/views/admin/trains/new.html.slim
.container
  .card
    .card-header
      h1
        = t('.title')
    .card-text
      .card-block
        = render 'form', train: @train, hidden: false
    .card-footer
      = link_to t('common.back'), admin_trains_path

app/views/admin/trains/show.html.slim
.container
  .card
    .card-header
      h3 = t('.title', train: @train.number)
    .card-text
      p
        ul
          li
            = t('admin.trains.index.current_station')
            ' :
            - if @train.current_station.nil?
              = t('.depot')
            - else
              =< @train.current_station.name
          li
            = t('common.route_title')
            ' :
            - if @train.route.nil?
              = t('.not_assigned')
            - else
              =< @train.route.title
        ul
          = t('.carriages')
          ' :
          - if @train.carriages.empty?
            = t('.no_carriages')
          - else
            - @train.sorted_carriages.each do |carriage|
              li = link_to "##{carriage.number}", [:admin, carriage.becomes(Carriage)]
        br

  =<> link_to t('.add_carriages'), new_admin_train_carriage_path(@train)
  | |
  =<> link_to t('common.edit'), edit_admin_train_path(@train)
  | |
  =<> link_to t('common.back'), admin_trains_path